# SwiftLint configuration for vibe-runner

included:
  - apps

excluded:
  - apps/**/Build
  - apps/**/.build
  - apps/**/DerivedData

# Rule configuration
disabled_rules:
  - trailing_whitespace # Let SwiftFormat handle this
  - line_length # Can be noisy for SwiftUI

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Customizations
force_cast: warning
force_try: warning
identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - ok
    - hr
    - vm
type_body_length:
  warning: 300
  error: 500
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 50
  error: 100
